#!/usr/bin/env node
/**
 * Assembles Starlight's src/content/docs/ and public/ from the promptfoo eval run write-ups at
 * packages/meteoswiss-forecast-evals/docs/results/ — the only content this public site serves.
 * Deliberately scoped to just that: internal docs (plans, sessionlogs, research, test-reports)
 * are not synced at all, by design (2026-07-18 re-scope per Max — see the sessionlog for the
 * full include/exclude rationale).
 *
 * Each synced run page gets two things injected right after its frontmatter: a link to its
 * paired promptfoo HTML snapshot (if one exists — the snapshot itself lives outside the content
 * collection, in public/, invisible to the autogenerated sidebar, so it would otherwise be
 * unreachable), and a short "About this run" editorial blurb from editorial/<slug>.md — light,
 * site-only prose explaining what the run tests and how to read it, kept separate from the
 * run's own (more technical) write-up. A run without a paired editorial stub is skipped
 * entirely rather than published without one — see loadEditorial.
 *
 * Also writes src/data/runs.generated.json, a manifest of {slug, title, teaser, href} for every
 * published run, imported by the homepage to render its teaser list.
 *
 * Idempotent: clears the sync targets before every run, so a renamed/removed source file doesn't
 * leave a stale copy behind.
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BASE } from '../site.config.mjs';

const PACKAGE_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const REPO_ROOT = join(PACKAGE_ROOT, '..', '..');

const CONTENT_DOCS_DIR = join(PACKAGE_ROOT, 'src', 'content', 'docs');
// This site is public and gets linked to from blog posts / other docs — the permalink prefix is
// a deliberate, final choice (2026-07-18, per Max), not an accident of the source directory
// layout. Do not rename without checking: it breaks every external link already handed out.
// URL path (always forward-slash), independent of RUNS_DEST_DIR's filesystem join below.
const RUNS_URL_PREFIX = 'runs';
const RUNS_DEST_DIR = join(CONTENT_DOCS_DIR, 'runs');
const EDITORIAL_DIR = join(PACKAGE_ROOT, 'editorial');
const DATA_DIR = join(PACKAGE_ROOT, 'src', 'data');
const RUNS_MANIFEST_PATH = join(DATA_DIR, 'runs.generated.json');
const PUBLIC_RESULTS_SUBPATH = 'forecast-evals-results';
const PUBLIC_RESULTS_DIR = join(PACKAGE_ROOT, 'public', PUBLIC_RESULTS_SUBPATH);
const FORECAST_EVALS_RESULTS_DIR = join(
  REPO_ROOT,
  'packages',
  'meteoswiss-forecast-evals',
  'docs',
  'results',
);
// The source write-ups are immutable records that link to sibling repo files with relative
// paths (e.g. `../../README.md`) — correct within the repo, but there is no repo checkout on
// the published site, so those 404 once synced. Rewritten to absolute GitHub blob URLs at sync
// time rather than editing the immutable source.
const GITHUB_BLOB_BASE = 'https://github.com/eins78/meteoswiss-llm-tools/blob/main';

type RunManifestEntry = {
  slug: string;
  title: string;
  teaser: string;
  href: string;
};

function walkFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isSymbolicLink()) continue;
    if (entry.isDirectory()) {
      out.push(...walkFiles(full));
    } else if (entry.isFile()) {
      out.push(full);
    }
  }
  return out;
}

function titleFromContent(markdown: string, fallbackName: string): string {
  const h1 = markdown.match(/^#\s+(.+)$/m);
  if (h1) return h1[1].trim();
  return basename(fallbackName)
    .replace(/\.md$/, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function ensureFrontmatter(markdown: string, fallbackName: string): string {
  if (markdown.startsWith('---\n')) return markdown; // already has frontmatter, leave as-is
  const title = titleFromContent(markdown, fallbackName);
  // Escape backslashes before quotes so a literal backslash doesn't get swallowed into a
  // still-unescaped quote's escape sequence.
  const escapedTitle = title.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  return `---\ntitle: "${escapedTitle}"\n---\n\n${markdown}`;
}

/**
 * Rewrites markdown links whose href is relative (starts with `../`, resolved against the
 * source write-up's own directory) to absolute GitHub blob URLs. The source write-ups
 * (immutable — never hand-edited) link to sibling repo files like `../../README.md` or
 * `../spec.md`; those resolve fine in a repo checkout but there is no checkout on the published
 * site, so left as-is they 404 (see docs/sessionlogs — the 2026-07-18 defect Max found).
 */
function rewriteRelativeLinks(markdown: string, sourceFile: string): string {
  const sourceDir = dirname(sourceFile);
  return markdown.replace(/\]\((\.\.\/[^)]+)\)/g, (_match, href: string) => {
    const repoRelativePath = relative(REPO_ROOT, resolve(sourceDir, href)).split(sep).join('/');
    return `](${GITHUB_BLOB_BASE}/${repoRelativePath})`;
  });
}

/**
 * A run is only published if it has a paired editorial/<slug>.md stub — a required "teaser:"
 * frontmatter field plus a body of light explanatory prose. Deliberately strict: a future dated
 * run added without editorial is skipped (with a loud warning) rather than published without the
 * explanatory framing Max asked every run to have.
 */
function loadEditorial(slug: string): { teaser: string; body: string } | null {
  const path = join(EDITORIAL_DIR, `${slug}.md`);
  if (!existsSync(path)) return null;
  const raw = readFileSync(path, 'utf8');
  const match = raw.match(/^---\n([\s\S]*?)\n---\n\n?([\s\S]*)$/);
  if (!match) throw new Error(`editorial/${slug}.md: missing frontmatter block`);
  const [, frontmatter, body] = match;
  const teaserMatch = frontmatter.match(/^teaser:\s*"((?:[^"\\]|\\.)*)"\s*$/m);
  if (!teaserMatch) throw new Error(`editorial/${slug}.md: missing "teaser" frontmatter field`);
  return { teaser: teaserMatch[1].replace(/\\"/g, '"'), body: body.trim() };
}

/**
 * Inserts the editorial blurb and (if present) the embedded promptfoo results snapshot right
 * after the frontmatter, before the run's own write-up — orienting a public reader with the
 * actual eval output before the more technical prose. The link to the snapshot comes BEFORE the
 * iframe, not after: the iframe is ~full-viewport tall and scrolls its own huge embedded report
 * internally, so a reader whose cursor is over it while scrolling never reaches page content
 * placed after it (confirmed as the cause of Max's "I don't see any export links" 2026-07-18
 * report — the link existed, just past a scroll trap). Astro passes raw HTML through untouched
 * in markdown (verified against a real build), so the iframe itself renders fine; it's kept
 * below the link as a secondary, "expand inline" affordance.
 */
function injectSiteContent(
  markdown: string,
  slug: string,
  title: string,
  editorialBody: string,
  snapshotSlugs: Set<string>,
): string {
  const parts = [`## About this run\n\n${editorialBody}`];
  if (snapshotSlugs.has(slug)) {
    // Root-relative markdown links/URLs are NOT rewritten by Astro's `base` handling at build
    // time (verified: an unprefixed link survived a full build unchanged) — the prefix has to
    // be baked in here.
    const snapshotUrl = `${BASE}/${PUBLIC_RESULTS_SUBPATH}/${slug}.html`;
    const escapedTitle = title.replace(/"/g, '&quot;');
    parts.push(
      [
        '## Full results',
        '',
        `**[Open the full promptfoo results ↗](${snapshotUrl})** — the complete, interactive report (all providers, all rows, searchable). Also embedded below, scrollable in place:`,
        '',
        `<iframe src="${snapshotUrl}" title="${escapedTitle} — promptfoo eval results" loading="lazy" style="width: 100%; height: 85vh; min-height: 480px; border: 1px solid var(--sl-color-gray-5); border-radius: 0.5rem;"></iframe>`,
      ].join('\n'),
    );
  }
  const frontmatterEnd = markdown.indexOf('---\n', 4) + 4; // markdown already has frontmatter here
  return `${markdown.slice(0, frontmatterEnd)}\n${parts.join('\n\n')}\n\n${markdown.slice(frontmatterEnd)}`;
}

function syncHtmlSnapshots(): { count: number; slugs: Set<string> } {
  const slugs = new Set<string>();
  if (!existsSync(FORECAST_EVALS_RESULTS_DIR)) return { count: 0, slugs };
  mkdirSync(PUBLIC_RESULTS_DIR, { recursive: true });
  let count = 0;
  for (const file of walkFiles(FORECAST_EVALS_RESULTS_DIR)) {
    if (!file.endsWith('.html')) continue;
    const rel = relative(FORECAST_EVALS_RESULTS_DIR, file);
    const destPath = join(PUBLIC_RESULTS_DIR, rel);
    mkdirSync(dirname(destPath), { recursive: true });
    copyFileSync(file, destPath); // verbatim — never parsed, never a content-collection page
    slugs.add(basename(rel, '.html'));
    count++;
  }
  return { count, slugs };
}

function syncRuns(snapshotSlugs: Set<string>): RunManifestEntry[] {
  if (!existsSync(FORECAST_EVALS_RESULTS_DIR)) return [];
  mkdirSync(RUNS_DEST_DIR, { recursive: true });
  const manifest: RunManifestEntry[] = [];
  for (const file of walkFiles(FORECAST_EVALS_RESULTS_DIR)) {
    if (!file.endsWith('.md')) continue;
    const rel = relative(FORECAST_EVALS_RESULTS_DIR, file);
    const slug = basename(rel, '.md');
    const editorial = loadEditorial(slug);
    if (!editorial) {
      console.warn(
        `⚠️  skipping ${rel} — no editorial/${slug}.md stub (required "teaser" + explanatory prose for publication)`,
      );
      continue;
    }
    const raw = rewriteRelativeLinks(readFileSync(file, 'utf8'), file);
    const withFrontmatter = ensureFrontmatter(raw, rel);
    const title = titleFromContent(raw, rel);
    const destPath = join(RUNS_DEST_DIR, rel);
    mkdirSync(dirname(destPath), { recursive: true });
    writeFileSync(
      destPath,
      injectSiteContent(withFrontmatter, slug, title, editorial.body, snapshotSlugs),
      'utf8',
    );
    manifest.push({
      slug,
      title,
      teaser: editorial.teaser,
      href: `${RUNS_URL_PREFIX}/${slug}/`,
    });
  }
  // Slugs are date-prefixed (YYYY-MM-DD-*) — sort descending so the newest run leads the list.
  manifest.sort((a, b) => b.slug.localeCompare(a.slug));
  return manifest;
}

function clearSyncTargets(): void {
  if (existsSync(CONTENT_DOCS_DIR)) {
    for (const entry of readdirSync(CONTENT_DOCS_DIR)) {
      if (entry === 'index.mdx') continue; // hand-authored homepage
      rmSync(join(CONTENT_DOCS_DIR, entry), { recursive: true, force: true });
    }
  }
  if (existsSync(PUBLIC_RESULTS_DIR)) rmSync(PUBLIC_RESULTS_DIR, { recursive: true, force: true });
}

function main(): void {
  clearSyncTargets();

  // Snapshots must sync first: syncRuns needs to know which slugs have a paired .html file so
  // it can link to it inline (see injectSiteContent).
  const { count: htmlCount, slugs: snapshotSlugs } = syncHtmlSnapshots();
  console.log(
    `synced ${htmlCount} static HTML snapshot(s) -> public/${PUBLIC_RESULTS_SUBPATH}/ (verbatim, not content pages)`,
  );

  const manifest = syncRuns(snapshotSlugs);
  console.log(
    `synced ${manifest.length} eval run(s) -> ${relative(PACKAGE_ROOT, RUNS_DEST_DIR)}`,
  );

  mkdirSync(DATA_DIR, { recursive: true });
  writeFileSync(RUNS_MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

  if (manifest.length === 0) {
    throw new Error(
      'sync-content: 0 runs published — check FORECAST_EVALS_RESULTS_DIR resolution and that each results .md has a paired editorial/ stub',
    );
  }
}

main();
