#!/usr/bin/env node
/**
 * Assembles Starlight's src/content/docs/ and public/ from two source trees that live outside
 * this package: the repo-root docs/ folder, and packages/meteoswiss-forecast-evals/docs/results/.
 * Neither source has Starlight-shaped frontmatter, and Starlight only reads from one directory —
 * see docs/plans/2026-07-11-pages-starlight-implementation-plan.md for the design.
 *
 * Idempotent: clears the sync targets before every run, so a renamed/removed source file doesn't
 * leave a stale copy behind.
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { basename, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BASE } from '../site.config.mjs';

type ContentSource = {
  srcDir: string;
  destSubdir: string;
};

const PACKAGE_ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const REPO_ROOT = join(PACKAGE_ROOT, '..', '..');

const CONTENT_DOCS_DIR = join(PACKAGE_ROOT, 'src', 'content', 'docs');
const PUBLIC_RESULTS_SUBPATH = 'forecast-evals-results';
const PUBLIC_RESULTS_DIR = join(PACKAGE_ROOT, 'public', PUBLIC_RESULTS_SUBPATH);
const FORECAST_EVALS_RESULTS_DIR = join(
  REPO_ROOT,
  'packages',
  'meteoswiss-forecast-evals',
  'docs',
  'results',
);

const SOURCES: ContentSource[] = [
  { srcDir: join(REPO_ROOT, 'docs'), destSubdir: '' },
  { srcDir: FORECAST_EVALS_RESULTS_DIR, destSubdir: join('forecast-evals', 'results') },
];

function walkFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    // Skip symlinks outright — docs/plans/active/*.md and docs/plans/delivered/*.md are literal
    // symlinks back to sibling files in docs/plans/; following them would double-list the same
    // plan under two sidebar paths.
    if (entry.isSymbolicLink()) continue;
    if (entry.isDirectory()) {
      out.push(...walkFiles(full));
    } else if (entry.isFile()) {
      out.push(full);
    }
  }
  return out;
}

function titleFromContent(markdown: string, fallbackName: string): string {
  const h1 = markdown.match(/^#\s+(.+)$/m);
  if (h1) return h1[1].trim().replace(/"/g, "'");
  return fallbackName
    .replace(/\.md$/, '')
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function ensureFrontmatter(markdown: string, fallbackName: string): string {
  if (markdown.startsWith('---\n')) return markdown; // already has frontmatter, leave as-is
  const title = titleFromContent(markdown, fallbackName);
  const escapedTitle = title.replace(/"/g, '\\"');
  return `---\ntitle: "${escapedTitle}"\n---\n\n${markdown}`;
}

/**
 * If a writeup at docs/results/<slug>.md has a paired promptfoo HTML snapshot at
 * docs/results/<slug>.html, insert a link to it right after the frontmatter — otherwise the
 * snapshot (which lives outside the content collection, in public/, invisible to the
 * autogenerated sidebar) would be unreachable from anywhere on the built site.
 */
function withSnapshotLink(markdown: string, slug: string, snapshotSlugs: Set<string>): string {
  if (!snapshotSlugs.has(slug)) return markdown;
  // Root-relative markdown links are NOT rewritten by Astro's `base` handling at build time
  // (verified: an unprefixed link survived a full build unchanged) — the prefix has to be
  // baked in here.
  const link = `[View the full static run snapshot →](${BASE}/${PUBLIC_RESULTS_SUBPATH}/${slug}.html)`;
  const frontmatterEnd = markdown.indexOf('---\n', 4) + 4; // markdown already has frontmatter here
  return `${markdown.slice(0, frontmatterEnd)}\n${link}\n${markdown.slice(frontmatterEnd)}`;
}

function syncMarkdownTree(srcDir: string, destDir: string, snapshotSlugs: Set<string>): number {
  if (!existsSync(srcDir)) return 0;
  mkdirSync(destDir, { recursive: true });
  let count = 0;
  for (const file of walkFiles(srcDir)) {
    if (!file.endsWith('.md')) continue;
    const rel = relative(srcDir, file);
    const destPath = join(destDir, rel);
    mkdirSync(dirname(destPath), { recursive: true });
    const raw = readFileSync(file, 'utf8');
    const withFrontmatter = ensureFrontmatter(raw, rel);
    const slug = basename(rel, '.md');
    writeFileSync(destPath, withSnapshotLink(withFrontmatter, slug, snapshotSlugs), 'utf8');
    count++;
  }
  return count;
}

function syncHtmlSnapshots(srcDir: string, destDir: string): { count: number; slugs: Set<string> } {
  const slugs = new Set<string>();
  if (!existsSync(srcDir)) return { count: 0, slugs };
  mkdirSync(destDir, { recursive: true });
  let count = 0;
  for (const file of walkFiles(srcDir)) {
    if (!file.endsWith('.html')) continue;
    const rel = relative(srcDir, file);
    const destPath = join(destDir, rel);
    mkdirSync(dirname(destPath), { recursive: true });
    copyFileSync(file, destPath); // verbatim — never parsed, never a content-collection page
    slugs.add(basename(rel, '.html'));
    count++;
  }
  return { count, slugs };
}

function clearSyncTargets(): void {
  for (const { destSubdir } of SOURCES) {
    const target = destSubdir ? join(CONTENT_DOCS_DIR, destSubdir) : CONTENT_DOCS_DIR;
    if (!existsSync(target)) continue;
    for (const entry of readdirSync(target)) {
      // Never wipe index.mdx (the hand-authored homepage) when clearing the root content dir.
      if (destSubdir === '' && entry === 'index.mdx') continue;
      rmSync(join(target, entry), { recursive: true, force: true });
    }
  }
  if (existsSync(PUBLIC_RESULTS_DIR)) rmSync(PUBLIC_RESULTS_DIR, { recursive: true, force: true });
}

function main(): void {
  clearSyncTargets();

  // Snapshots must sync first: syncMarkdownTree needs to know which slugs have a paired .html
  // file so it can link to it inline (see withSnapshotLink).
  const { count: htmlCount, slugs: snapshotSlugs } = syncHtmlSnapshots(
    FORECAST_EVALS_RESULTS_DIR,
    PUBLIC_RESULTS_DIR,
  );
  console.log(
    `synced ${htmlCount} static HTML snapshot(s) -> public/${PUBLIC_RESULTS_SUBPATH}/ (verbatim, not content pages)`,
  );

  let totalMd = 0;
  for (const { srcDir, destSubdir } of SOURCES) {
    const destDir = destSubdir ? join(CONTENT_DOCS_DIR, destSubdir) : CONTENT_DOCS_DIR;
    const count = syncMarkdownTree(srcDir, destDir, snapshotSlugs);
    totalMd += count;
    console.log(
      `synced ${count} markdown file(s) from ${relative(REPO_ROOT, srcDir)} -> ${relative(PACKAGE_ROOT, destDir)}`,
    );
  }

  if (totalMd === 0) {
    throw new Error('sync-content: found 0 markdown files across all sources — check REPO_ROOT resolution');
  }
}

main();
