// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { SITE, BASE } from './site.config.mjs';

// https://astro.build/config
export default defineConfig({
	site: SITE,
	base: BASE,
	integrations: [
		starlight({
			title: 'MeteoSwiss LLM Tools',
			// Matches the default Starlight resolves anyway (public/favicon.svg) — set explicitly
			// so the weather-emoji favicon is documented, not just an accident of file placement.
			favicon: '/favicon.svg',
			social: [
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/eins78/meteoswiss-llm-tools' },
			],
			// One group per top-level docs/ folder, autogenerated from content so new files show up
			// without a config change. See the implementation plan for why `forecast-evals-results`
			// (the raw promptfoo HTML snapshots in public/) isn't listed here — autogenerate only
			// scans src/content/docs/, and those files are deliberately outside that pipeline.
			sidebar: [
				{ label: 'Plans', items: [{ autogenerate: { directory: 'plans' } }] },
				{ label: 'Sessionlogs', items: [{ autogenerate: { directory: 'sessionlogs' } }] },
				{ label: 'Research', items: [{ autogenerate: { directory: 'research' } }] },
				{ label: 'Test Reports', items: [{ autogenerate: { directory: 'test-reports' } }] },
				{
					label: 'Forecast Evals — Results',
					items: [{ autogenerate: { directory: 'forecast-evals/results' } }],
				},
			],
		}),
	],
});
